### ISSUE TITLE
Use API v2

### ISSUE THREAD

**Issue by jayvdb** [hermanzdosilovic/gauss#1]
https://productive.io/api/v1 is now 404

**Comment by jayvdb** [comment]
https://github.com/productiveio/api_client might be an option.

**Comment by hermanzdosilovic** [comment]
Hi @jayvdb,

You are right. This project is deprecated and you should use their official API client https://github.com/productiveio/api_client.

**Comment by jayvdb** [comment]
Sorry I was meaning this tool could use that gem for API usage.

That gem doesnt include a CLI, so your tool is still very much needed.
